{{- $service_account_name := include "vault-client.serviceAccountName" . -}}
{{- $labels := include "vault-client.labels" . | nindent 4 -}}
{{- range $namespace := .Values.serviceAccount.namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service_account_name }}
  namespace: {{ $namespace }}
  labels: {{ $labels }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $service_account_name }}
  namespace: {{ $namespace }}
  annotations:
    "kubernetes.io/service-account.name": vault-auth-service-account
  labels: {{ $labels }}
type: kubernetes.io/service-account-token
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $service_account_name }}-role-binding
  labels: {{ $labels }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
{{- range $namespace := .Values.serviceAccount.namespaces }}
  - kind: ServiceAccount
    name: {{ $service_account_name }}
    namespace: {{ $namespace }}
{{- end }}