vault-secrets-operator:
  defaultAuthMethod:
    namespace: default
    enabled: true
    mount:  default-k8s-cluster-auth-mount
    method: kubernetes
    kubernetes:
      role: "vso-auth-role"
      serviceAccount: vault-auth-service-account
      tokenAudiences: ["vault"]

  defaultVaultConnection:
    enabled: true
    address: "http://vault.vault.svc.cluster.local:8200"
    skipTLSVerify: true
  controller:
    replicas: 1

serviceAccount:
  name: vault-auth-service-account
  namespaces:
    - vault-secrets-operator-system
    - micro-v2
    - app
