# cd infra/env-dev/3-vault-client-vso
# kubectl config use-context local-k8s-2
# helm diff upgrade vault-secrets-operator ../../0-modules/3-vault-client-vso -n vault-secrets-operator-system -f local-k8s-2-vso.values.yaml

vault-secrets-operator:
  defaultAuthMethod:
    namespace: vault-secrets-operator-system
    mount:  local-k8s-2-auth-mount
  defaultVaultConnection:
    enabled: true
    address: "{VAULT_SERVER_ADDRESS}"

serviceAccount:
  name:  vault-auth-service-account
  namespaces:
    - payment
    - data-consumer
    - category
    - vault-secrets-operator-system